### ISSUE TITLE
roscore in aerostack virtual machine

### ISSUE THREAD

**Issue by jcanoj** [Vision4UAV/Aerostack#12]
Hello. 
Is $ roscore functional in the provided virtual machine (ref https://github.com/Vision4UAV/Aerostack/wiki/Aerostack-Virtual-Machine)? It doesn't seem to work out the box for me.

**Comment by joselusl** [comment]
Hi,
It should be functional..
Have you execute the command "source $AEROSTACK_STACK/setup.sh" before executing "roscore"?
You need to source to your ROS workspace!
Bests
