### ISSUE TITLE
Error al isntalar Aerostack

### ISSUE THREAD

**Issue by patrilopez** [Vision4UAV/Aerostack#15]
Hola, 
estoy intentando instalar Aerostack en un ordenador con Ubuntu 14.04 y ROS Jade, pero me da el siguiente error :fatal error: qwt/qwt_plot_curve.h: No existe el archivo o el directorio
 #include <qwt/qwt_plot_curve.h>
He intentado instalar qwt por otro lado, pero aún así me sigue dando el mismo error al intentar instalar Aerostack. ¿Qué puedo hacer?

Copio lo que me aparece en el terminal:
  from /home/usuario/workspace/ros/aerostack_catkin_ws/src/aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/src/controller/source/main_window.cpp:12:
/home/usuario/workspace/ros/aerostack_catkin_ws/src/aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/src/controller/source/../include/data_plot.h:14:32: fatal error: qwt/qwt_plot_curve.h: No existe el archivo o el directorio
 #include <qwt/qwt_plot_curve.h>
                                ^
compilation terminated.
[ 80%] Built target rosserial_server_serial_node
Scanning dependencies of target mavros_plugins
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/dummy.cpp.o
[ 80%] Building CXX object aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/CMakeFiles/human_machine_interface.dir/src/controller/source/images_receiver.cpp.o
[ 80%] Building CXX object aerostack_stack/stack_deprecated/common/drone_module_interface/CMakeFiles/droneModuleInterfaceROS.dir/src/source/drone_iarc14_brain_interface.cpp.o
Linking CXX executable /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/rosserial_server/socket_node
[ 80%] Built target rosserial_server_socket_node
Scanning dependencies of target ardrone_autonomy_generate_messages
[ 80%] Built target ardrone_autonomy_generate_messages
Scanning dependencies of target ardrone_autonomy_gencpp
[ 80%] Built target ardrone_autonomy_gencpp
Scanning dependencies of target aruco_eye_ros
Scanning dependencies of target driverParrotARDroneROSModule
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_parrot_ardrone/driver_parrot_ardrone_process/CMakeFiles/driverParrotARDroneROSModule.dir/src/source/parrotARDroneOuts.cpp.o
[ 80%] Building CXX object aerostack_stack/stack/feature_extraction_system/aruco_eye/aruco_eye/aruco_eye_ros/CMakeFiles/aruco_eye_ros.dir/src/source/aruco_eye_ros_detector.cpp.o
Linking CXX executable /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/mavros/gcs_bridge
[ 80%] Built target gcs_bridge
Scanning dependencies of target droneArchitectureRvizROSModule
[ 80%] Building CXX object aerostack_stack/stack/ground_control_system/rviz/droneArchitectureRvizInterfaceROSModule/CMakeFiles/droneArchitectureRvizROSModule.dir/src/source/swarmAgentInterface.cpp.o
[ 80%] [ 80%] Building CXX object aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/CMakeFiles/human_machine_interface.dir/src/controller/source/control_panel.cpp.o
Building CXX object aerostack_stack/stack_deprecated/common/drone_module_interface/CMakeFiles/droneModuleInterfaceROS.dir/src/source/droneModuleInterfaceList.cpp.o
make[2]: *** [aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/CMakeFiles/human_machine_interface.dir/src/controller/source/main_window.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
[ 80%] Building CXX object aerostack_stack/stack/feature_extraction_system/aruco_eye/aruco_eye/aruco_eye_ros/CMakeFiles/aruco_eye_ros.dir/src/source/aruco_eye_ros_display.cpp.o
Linking CXX executable /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/mavros/mavros_node
[ 80%] Built target mavros_node
Scanning dependencies of target EKFSimulatorRvizROSModuleNode
[ 80%] Building CXX object aerostack_stack/stack/ground_control_system/rviz/droneEkfSimulatorRvizROSModule/CMakeFiles/EKFSimulatorRvizROSModuleNode.dir/src/source/EKFSimulatorRvizROSModuleNode.cpp.o
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/sys_status.cpp.o
Linking CXX shared library /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/libdroneModuleInterfaceROS.so
[ 80%] Built target droneModuleInterfaceROS
Scanning dependencies of target SimulatorRvizROSModuleNode
[ 80%] Building CXX object aerostack_stack/stack/ground_control_system/rviz/droneSimulatorRvizROSModule/CMakeFiles/SimulatorRvizROSModuleNode.dir/src/source/SimulatorRvizROSModuleNode.cpp.o
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_parrot_ardrone/driver_parrot_ardrone_process/CMakeFiles/driverParrotARDroneROSModule.dir/src/source/parrotARDroneInps.cpp.o
make[1]: *** [aerostack_stack/stack/ground_control_system/human_machine_interface/human_machine_interface_process/CMakeFiles/human_machine_interface.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[ 80%] Building CXX object aerostack_stack/stack/ground_control_system/rviz/droneArchitectureRvizInterfaceROSModule/CMakeFiles/droneArchitectureRvizROSModule.dir/src/source/RvizInterfaceROSModule.cpp.o
[ 80%] [ 80%] Building CXX object aerostack_stack/stack/ground_control_system/rviz/droneArchitectureRvizInterfaceROSModule/CMakeFiles/droneArchitectureRvizROSModule.dir/src/source/RvizInteractiveMarkerDisplay.cpp.o
Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/sys_time.cpp.o
Linking CXX executable /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/droneEkfSimulatorRvizROSModule/EKFSimulatorRvizROSModuleNode
[ 80%] Built target EKFSimulatorRvizROSModuleNode
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/imu_pub.cpp.o
Linking CXX shared library /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/libdriverParrotARDroneROSModule.so
[ 80%] Built target driverParrotARDroneROSModule
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/param.cpp.o
Linking CXX executable /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/droneSimulatorRvizROSModule/SimulatorRvizROSModuleNode
Linking CXX shared library /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/libaruco_eye_ros.so
[ 80%] Built target SimulatorRvizROSModuleNode
[ 80%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/waypoint.cpp.o
[ 80%] Built target aruco_eye_ros
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/rc_io.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/command.cpp.o
Linking CXX shared library /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/libdroneArchitectureRvizROSModule.so
[ 81%] Built target droneArchitectureRvizROSModule
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/local_position.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/global_position.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/setpoint_position.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/safety_area.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/3dr_radio.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/setpoint_velocity.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/setpoint_accel.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/setpoint_attitude.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/setpoint_raw.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/vfr_hud.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/ftp.cpp.o
[ 81%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/actuator_control.cpp.o
[ 82%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/manual_control.cpp.o
[ 82%] Building CXX object aerostack_stack/stack/hardware_interface/drivers_platforms/driver_pixhawk/mavros/mavros/CMakeFiles/mavros_plugins.dir/src/plugins/altitude.cpp.o
Linking CXX shared library /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/libmavros_plugins.so
[ 82%] Built target mavros_plugins
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by martin-molina** [comment]
Parece ser que estás utilizando una versión de Qwt desactualizada. Prueba por ejemplo:

sudo apt-get install libqwt6 libqwt-dev

**Comment by patrilopez** [comment]
Muchas gracias! He conseguido instalarlo haciendo lo que me has comentado.
Aunque, ahora al intentar lanzar Aerostack me da error. Siguiendo la guía escribo el siguiente comando en el terminal: ./ardrone_basic.sh
Al hacerlo se abren nuevas ventanas de terminal y en una de ellas aparece el siguiente mensaje de error:
process[drone1/human_machine_interface_process-1]: started with pid [6685]
*** Error in `/home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/human_machine_interface/human_machine_interface': realloc(): invalid pointer: 0x000000000092fda0 ***
[drone1/human_machine_interface_process-1] process has died [pid 6685, exit code -6, cmd /home/usuario/workspace/ros/aerostack_catkin_ws/devel/lib/human_machine_interface/human_machine_interface __name:=human_machine_interface_process __log:=/home/usuario/.ros/log/522f914e-5a51-11e7-993e-00224dabcf6a/drone1-human_machine_interface_process-1.log].
log file: /home/usuario/.ros/log/522f914e-5a51-11e7-993e-00224dabcf6a/drone1-human_machine_interface_process-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

¿Cómo podría solucionarlo?
Gracias de antemano!

**Comment by martin-molina** [comment]
Vuelve a ejecutar el script de instalación de dependencias tal como se indica en la guía de instalación:

$AEROSTACK_STACK/installation/installation_dep_script.sh

Para revisar la correcta instalación de las distintas versiones de Qt y Opencv puedes ejecutar el siguiente comando:

sudo apt-get install libopencv-dev opencv-data ros-jade-opencv-apps libqt4-dev libqt4-core

Después deberías intentar volver a compilar y comprobar si funciona. 

Avísanos por favor con el resultado.
