### ISSUE TITLE
Aerostack - Gazebo

### ISSUE THREAD

**Issue by JacekCieslak95** [Vision4UAV/Aerostack#18]
Hello!
I am trying to simulate AR.Drone 2.0  in Gazebo, and control it by Aerostack HMI. 
I have tum_simulator installed in  ~/catkin_ws, and Aerostack in ~/workspace/ros/aerostack_catkin_ws
Running 

> roslaunch cvg_sim_gazebo ardrone_testworld.launch 

 command opens gazebo with test world, but (as I saw in rqt_graph) nodes and topics are not connected with those created by Aerostack. Is there a way to connect them? Or maybe there is other solution of simulation UAVs with Aerostack? 

Using Ubuntu 14.04 and ROS Jade

**Comment by martin-molina** [comment]
Aerostack is not directly connected now to Gazebo with AR Drone 2.0. It would be possible to connect them (e.g., by remapping Aerostack topics) but this can require certain amount of effort.

We sometimes use a simple simulator and the RViz viewer. For example, you can use the following script (in folder launchers):

> simulated_quadrotor_basic.sh
