### ISSUE TITLE
Using "Guided by TML mission"

### ISSUE THREAD

**Issue by JacekCieslak95** [Vision4UAV/Aerostack#20]
Hello!
I am trying to use "Guided by TML mission" mode, but I am facing `A mission specification file was not found.` error. I am using simulated_quadrotor_basic.sh. I am sure, that I followed all instructions provided in Wiki. My mission_specification_file.xml is in /home/jacek/workspace/ros/aerostack_catkin_ws/src/aerostack_stack/configs/drone1, I used 
` roslaunch task_based_mission_planner_process task_based_mission_planner_process.launch
`
and I received:
```
process[drone1/task_based_mission_planner_process-1]: started with pid [25639]
File loaded without errors! Waiting to start ...
```
but, mission can not be started anyway.
Keyboard teleoperation, Python missions and Behavior trees are working without any problem.

**Comment by albertcp** [comment]
@JacekCieslak95 Thank you for your message. The error should have been corrected. To update Aerostack just type the following commands:

```bash
cd $AEROSTACK_STACK
git pull origin master
git submodule sync
git submodule update --init
```

And now your TML mission should work out of the box.
