### ISSUE TITLE
How to use "FOLLOW_OBJECT_IMAGE" behavior?

### ISSUE THREAD

**Issue by pkaczmarek95** [Vision4UAV/Aerostack#24]
Hello,

I am trying to write a python mission that includes "FOLLOW_OBJECT_IMAGE" behavior. The description of it says that "the operator selects the image to follow through the user interface" - however during executing of a mission I am not able to do it in any way in the "camera views" bookmark. How to use that behavior?

This is the simple mission I was trying to run to check how to use the behavior: https://pastebin.com/5Ks93QTr
I wanted drone to follow something for a certain amount of time. FOLLOW_OBJECT_IMAGE doesn't even appear in execution viewer. How to make it working properly?

EDIT: Page "catalog of processes" of Aerostack wiki says that I need to launch two required launch files. I was trying to find them and none of the them exist in my Aerostack installation. 

I've got one more question. In another topic it was mentioned that script that allows simulation of more than one drone was being prepared. When, more or less, is it going to be released?

Thanks for considering my problem.

**Comment by albertcp** [comment]
Hi!

This page of the [wiki](https://github.com/Vision4UAV/Aerostack/wiki/Catalog-of-Processes) has every process that need to be launched in order to use the behavior FOLLOW_OBJECT_IMAGE. Check if every of the processes mentioned are launched.
I see that the required launch files are not uploaded. I will write you as soon as I upload both files.

Regarding the other question, inside the launchers directory, you can find a script called "rvizInterface_Test.sh". You should run as many Aerostacks as drones you need and then you can visualise them by executing the script mentioned.

I hope you solve all your problems.

**Comment by JacekCieslak95** [comment]
I am trying to launch simulation script (simulated_quadrotor_basic.sh) with input argument, to launch many Aerostacks. I saw, that 

> NUMID_DRONE=$1
so first given argument should be an drone number. Running command 
./simulated_quadrotor_basic.sh 2
to give this drone NUMID_DRONE=2 gives strange result: Aerostack can't see roscore / master:
> roscore/master is not yet running, will wait for it to start

**Comment by pkaczmarek95** [comment]
Thanks, @albertcp , I have updated Aerostack and I have required files now. I was trying to run my mission mentioned in post #1. Following advices on the page 'processes' I launched:
droneTrackerEyeROSModule.launch
DroneIBVSControllerROSModule.launch
droneOpenTLDTranslatorROSModule.launch
and 
opentld_for_IBVSController.launch
opentld_gui_for_IBVSController.launch
After launching all of this (and my node that publish data from a webcam to /drone1/camera/front/image_raw) I had this nodes active:
![rosnodes](https://user-images.githubusercontent.com/26835508/34268493-33a813b0-e681-11e7-879b-42f94af53fec.jpg)
and new window TLD Gui appeared. However it was empty. 
![tld](https://user-images.githubusercontent.com/26835508/34269580-2df67c82-e685-11e7-90a2-3a3fa8ab5f5a.jpg)
Mission still doesn't even appear in execution viewer during a mission. How to use it properly?

**Comment by albertcp** [comment]
@JacekCieslak95 You can type ```./simulated_quadrotor_basic.sh 2 <roscore_ip>``` for now.

The problems you had seems to be related to the roscore IP. When you assign only the droneID it also changes the roscore IP. I'll write you as soon as the script is fixed.

**Comment by albertcp** [comment]
@pkaczmarek95 Which drone id are you using to launch Aerostack? 

Every Aerostack process should have the same drone_id to work properly. I can see from your ```rosnode list``` output that the processes you are launching have drone0 assigned, but I don't know the drone_id assigned to the Aerostack processes.

To launch any Aerostack process as droneX you can do 2 different things (Being X: 0,1,2,3,4...):
1. Add the process inside the launcher if they are not already. To do so, copy and paste one and change the process name and the .launch file.
2. When you launch the process via terminal add this parameter at the end of each process: ```drone_id_namespace:=droneX```. DroneX should be the same as the rest of Aersotack's processes. For example, with the behavior GO_TO_POINT the command has to be: ```roslaunch behavior_go_to_point behavior_go_to_point.launch drone_id_namespace:=drone1```

If this is the problem, the camera should be appeared when the behavior FOLLOW_OBJECT_IMAGE is activated.

**Comment by pkaczmarek95** [comment]
@albertcp 
Thanks, you were right, I modified launch files and change drone_id from 0 to 1 (as 1 is default drone_id for Aerostack). Now, after running all processes and aerostack my rosnode list looks like this:
https://pastebin.com/FGvTMXVH
There is some progress because FOLLOW_OBJECT_IMAGE finally appears in an execution viewer when i run a mission. However TLD Gui is still empty. Should I run something more?

**Comment by albertcp** [comment]
It should appear a freeze image of the drone the moment every process starts.

Is the TLD GUI still empty after executing the behavior FOLLOW_OBJECT_IMAGE?. 

Anyway, I'll make some tests to see if no image is received by the TLD GUI.
