### ISSUE TITLE
Checking battery level in a mission written in python

### ISSUE THREAD

**Issue by pkaczmarek95** [Vision4UAV/Aerostack#25]
Hello,

I'd like to know if there is any way to check the battery level during execution of mission. On your wiki I read that there is a belief "charge(battery, x)" but every time I try to use:
 success, unification = api.consultBelief('charge(self, ?X)')
I get the message that query was unsuccessful. I guess I am using it wrong way? Or is it one of these beliefs that will be implemented in the future?

**Comment by martin-molina** [comment]
In your question you say that you tried:
success, unification = api.consultBelief('charge(self, ?X)')
But the belief expression should be charge(battery,?X) instead of charge(self,?X).
Please, let us know if this solves the problem.

**Comment by martin-molina** [comment]
We have now this predicate for battery:
battery_level(self,?X)
The values of X are qualitative.

**Comment by pkaczmarek95** [comment]
@martin-molina  Thanks for reply, it works fine now.
