### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by soheil2017** [Vision4UAV/Aerostack#27]
Hi 
I got following error at the last step of installation 

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
audio_capture: No definition of [gstreamer0.10-plugins-ugly] for OS version [xenial]
rotors_simulator: Cannot locate rosdep definition for [rotors_hil_interface]
sound_play: No definition of [python-gst] for OS version [xenial]
audio_play: No definition of [gstreamer0.10-plugins-ugly] for OS version [xenial]
belief_manager: Cannot locate rosdep definition for [belief_parser]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
somebody could help me please? 

Also I am using ubuntu 16.04 (ROS-kinetic)

**Comment by albertcp** [comment]
Hi @soheil2017 ,

Thank you for reporting the issue. We will correct this problem as soon as possible.

However, Aerostack should work correctly although this error shows up.
