### ISSUE TITLE
basic behavior tutorial doesn't execute

### ISSUE THREAD

**Issue by markhamj** [Vision4UAV/Aerostack#29]
launch , land behaviors work in the behavior tree.   goto position (including relative position) appear to do nothing and the simulated quadrotor stays stationary

**Comment by albertcp** [comment]
Hi @markhamj ,

Can you send us more information about the problem? For example, if there is an error in any terminal and what says the error message.

**Comment by markhamj** [comment]
Closing issue.   After fixing some environment settings was able to execute simple behavior tree.
