### ISSUE TITLE
asctec_autopilot node not found

### ISSUE THREAD

**Issue by shlapion** [Vision4UAV/Aerostack#3]
Hi, 

I am trying to run the framework on an AscTec Pelican. 
I followed the launch sequence from the pelican_real_flight_instructions file.
When I run the launchfile asctec_driver_node I get the following error:
`ERROR: cannot launch node of type [asctec_autopilot/autopilot_node]: asctec_autopilot`
I have roscore started and also sourced the proper workspace.

Is there a specific AscTec SDK that I must flash the HL with?
I have tried both V2 and V3.
The OS on the Pelican is installed form the newest recovery image found on the AscTec wiki page.

**Comment by joselusl** [comment]
Hi,

We are using the catkinized version of asctec_drivers: http://wiki.ros.org/asctec_drivers
Please read all the associated documentation in this package regarding to flashing the AscTec Pelican. Note that our catkinized version (https://bitbucket.org/joselusl/asctec_drivers) is going to differ when compiling.

Bests

**Comment by hridaybavle** [comment]
Hi, 

The problem seems to be because the node is not being detected, not the SDK version atleast now. Can you check inside Aerostack/stack/droneDrivers/driversPlatforms/driverAsctecPelican/asctec_drivers if you have all the files regarding the package.

**Comment by joselusl** [comment]
I have fixed the environmental variables that were not properly set.
Please update everything (using the installer ;) )
Bests
