### ISSUE TITLE
When creating a new map

### ISSUE THREAD

**Issue by QiuMingZS** [Vision4UAV/Aerostack#30]
Dear professors,
    I'm trying to create a map and set a new mission. There is a question that whether I need to create a new folder that is called droneX(maybe drone15, which is not existed before). 
   Besides, when I'm creating a map, do I need to write a lot of xml files(for example, configFile.xml, ekf_state_estimator_config.xml, and so on)?

Thank you so much for your help!

**Comment by captjulian** [comment]
Hi 
I think you can create a new drone or just use current drone.
For configFile , you only create it when you need.
I hope it can help you.

Good luck

**Comment by QiuMingZS** [comment]
Thank you so much!
