### ISSUE TITLE
unknown type

### ISSUE THREAD

**Issue by QiuMingZS** [Vision4UAV/Aerostack#36]
When I launched the simulation, I can not get the image from the camera, and find:
 
* /drone1/camera/bottom/image_raw [unknown type]
* /drone1/camera/front/image_raw [unknown type]

What's the reason?

The complete code is as follows:
`guanzheng@guanzheng-CN15S:~$ rosnode info /drone1/graphical_user_interface_process
--------------------------------------------------------------------------------
Node [/drone1/graphical_user_interface_process]
Publications: 
 * /drone1/command/dAltitude [droneMsgsROS/droneDAltitudeCmd]
 * /drone1/command/dYaw [droneMsgsROS/droneDYawCmd]
 * /drone1/command/pitch_roll [droneMsgsROS/dronePitchRollCmd]
 * /drone1/droneControllerYawRefCommand [droneMsgsROS/droneYawRefCommand]
 * /drone1/droneMissionPlannerCommand [droneMsgsROS/droneMissionPlannerCommand]
 * /drone1/dronePositionRefs [droneMsgsROS/dronePositionRefCommandStamped]
 * /drone1/droneSpeedsRefs [droneMsgsROS/droneSpeeds]
 * /drone1/requested_action [droneMsgsROS/actionData]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /drone1/EstimatedPose_droneGMR_wrt_GFF [droneMsgsROS/dronePose]
 * /drone1/all_beliefs [droneMsgsROS/AllBeliefs]
 * /drone1/altitude [droneMsgsROS/droneAltitude]
 * /drone1/approved_action [unknown type]
 * /drone1/battery [droneMsgsROS/battery]
 * /drone1/behavior_event [droneMsgsROS/BehaviorEvent]
 * /drone1/camera/bottom/image_raw [unknown type]
 * /drone1/camera/front/image_raw [unknown type]
 * /drone1/camera/overlay/image_raw/big [sensor_msgs/Image]
 * /drone1/camera/overlay/image_raw/small [sensor_msgs/Image]
 * /drone1/command/dAltitude [droneMsgsROS/droneDAltitudeCmd]
 * /drone1/command/dYaw [droneMsgsROS/droneDYawCmd]
 * /drone1/command/high_level [droneMsgsROS/droneCommand]
 * /drone1/command/pitch_roll [droneMsgsROS/dronePitchRollCmd]
 * /drone1/completed_action [unknown type]
 * /drone1/completed_mission [droneMsgsROS/CompletedMission]
 * /drone1/current_task [unknown type]
 * /drone1/droneManagerStatus [unknown type]
 * /drone1/droneMissionHLCommandAck [unknown type]
 * /drone1/droneSpeedsRefs [droneMsgsROS/droneSpeeds]
 * /drone1/droneTrajectoryAbsRefCommand [droneMsgsROS/dronePositionTrajectoryRefCommand]
 * /drone1/estimated_pose [droneMsgsROS/dronePose]
 * /drone1/estimated_speeds [unknown type]
 * /drone1/event [unknown type]
 * /drone1/ground_speed [droneMsgsROS/vector2Stamped]
 * /drone1/imu [sensor_msgs/Imu]
 * /drone1/list_of_active_behaviors [droneMsgsROS/ListOfBehaviors]
 * /drone1/magnetometer [geometry_msgs/Vector3Stamped]
 * /drone1/obstacles [droneMsgsROS/obstaclesTwoDim]
 * /drone1/pressure [sensor_msgs/FluidPressure]
 * /drone1/process_error_unified_notification [droneMsgsROS/ProcessError]
 * /drone1/processes_performance [droneMsgsROS/ProcessDescriptorList]
 * /drone1/rotation_angles [geometry_msgs/Vector3Stamped]
 * /drone1/skills_list [unknown type]
 * /drone1/societyPose [droneMsgsROS/societyPose]
 * /drone1/status [droneMsgsROS/droneStatus]
 * /drone1/surface_inspection_image [unknown type]
 * /drone1/temperature [sensor_msgs/Temperature]
 * /drone1/trajectoryControllerPositionReferencesRebroadcast [droneMsgsROS/dronePose]
 * /drone1/trajectoryControllerSpeedReferencesRebroadcast [droneMsgsROS/droneSpeeds]
 * /drone1/wifiIsOk [std_msgs/Bool]
 * /public_event [unknown type]

Services: 
 * /drone1/graphical_user_interface_process/get_loggers
 * /drone1/graphical_user_interface_process/set_logger_level

contacting node http://guanzheng-CN15S:45068/ ...
Pid: 4948
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/graphical_user_interface_process
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/droneSimulator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/droneInterface
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/droneOdometryStateEstimator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dAltitude
    * to: /drone1/graphical_user_interface_process
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/dAltitude
    * to: /drone1/droneSimulator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dAltitude
    * to: /drone1/droneInterface
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dAltitude
    * to: /drone1/droneOdometryStateEstimator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dYaw
    * to: /drone1/graphical_user_interface_process
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/dYaw
    * to: /drone1/droneSimulator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dYaw
    * to: /drone1/droneInterface
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/dYaw
    * to: /drone1/droneOdometryStateEstimator
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/dronePositionRefs
    * to: /drone1/droneTrajectoryController
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/droneControllerYawRefCommand
    * to: /drone1/droneTrajectoryController
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/droneSpeedsRefs
    * to: /drone1/graphical_user_interface_process
    * direction: outbound
    * transport: INTRAPROCESS
 * topic: /drone1/droneSpeedsRefs
    * to: /drone1/droneTrajectoryController
    * direction: outbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/droneTrajectoryController (http://guanzheng-CN15S:33271/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/pitch_roll
    * to: /drone1/graphical_user_interface_process (http://guanzheng-CN15S:45068/)
    * direction: inbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/dAltitude
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/dAltitude
    * to: /drone1/droneTrajectoryController (http://guanzheng-CN15S:33271/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/dAltitude
    * to: /drone1/graphical_user_interface_process (http://guanzheng-CN15S:45068/)
    * direction: inbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/dYaw
    * to: /drone1/droneTrajectoryController (http://guanzheng-CN15S:33271/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/dYaw
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/dYaw
    * to: /drone1/graphical_user_interface_process (http://guanzheng-CN15S:45068/)
    * direction: inbound
    * transport: INTRAPROCESS
 * topic: /drone1/command/high_level
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/command/high_level
    * to: /drone1/behavior_go_to_point (http://guanzheng-CN15S:36197/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/imu
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/temperature
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/magnetometer
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/battery
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/altitude
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/rotation_angles
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/ground_speed
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/pressure
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/status
    * to: /drone1/droneSimulator (http://guanzheng-CN15S:39213/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/estimated_pose
    * to: /drone1/self_localization_selector_process (http://guanzheng-CN15S:34375/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/trajectoryControllerPositionReferencesRebroadcast
    * to: /drone1/droneTrajectoryController (http://guanzheng-CN15S:33271/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/trajectoryControllerSpeedReferencesRebroadcast
    * to: /drone1/droneTrajectoryController (http://guanzheng-CN15S:33271/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/camera/overlay/image_raw/big
    * to: /drone1/first_view_process (http://guanzheng-CN15S:37755/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/camera/overlay/image_raw/small
    * to: /drone1/first_view_process (http://guanzheng-CN15S:37755/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/process_error_unified_notification
    * to: /drone1/process_monitor_process_main (http://guanzheng-CN15S:37666/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/processes_performance
    * to: /drone1/process_monitor_process_main (http://guanzheng-CN15S:37666/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/wifiIsOk
    * to: /drone1/process_monitor_process_main (http://guanzheng-CN15S:37666/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/completed_mission
    * to: /drone1/task_based_mission_planner_process (http://guanzheng-CN15S:45047/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/obstacles
    * to: /drone1/droneObstacleProcessor (http://guanzheng-CN15S:43737/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/droneTrajectoryAbsRefCommand
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/droneTrajectoryAbsRefCommand
    * to: /drone1/droneTrajectoryPlanner (http://guanzheng-CN15S:38144/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/droneTrajectoryAbsRefCommand
    * to: /drone1/behavior_go_to_point (http://guanzheng-CN15S:36197/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/societyPose
    * to: /drone1/droneCommunicationManager (http://guanzheng-CN15S:43428/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/EstimatedPose_droneGMR_wrt_GFF
    * to: /drone1/droneOdometryStateEstimator (http://guanzheng-CN15S:38347/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/droneSpeedsRefs
    * to: /drone1/graphical_user_interface_process (http://guanzheng-CN15S:45068/)
    * direction: inbound
    * transport: INTRAPROCESS
 * topic: /drone1/droneSpeedsRefs
    * to: /drone1/droneInterface (http://guanzheng-CN15S:33452/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/droneSpeedsRefs
    * to: /drone1/behavior_go_to_point (http://guanzheng-CN15S:36197/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/list_of_active_behaviors
    * to: /drone1/behavior_coordinator_process (http://guanzheng-CN15S:45774/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/all_beliefs
    * to: /drone1/belief_manager_process (http://guanzheng-CN15S:36049/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/behavior_event
    * to: /drone1/behavior_self_localize_by_odometry (http://guanzheng-CN15S:38824/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/behavior_event
    * to: /drone1/behavior_take_off (http://guanzheng-CN15S:35132/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/behavior_event
    * to: /drone1/behavior_go_to_point (http://guanzheng-CN15S:36197/)
    * direction: inbound
    * transport: TCPROS
 * topic: /drone1/behavior_event
    * to: /drone1/behavior_land (http://guanzheng-CN15S:38670/)
    * direction: inbound
    * transport: TCPROS
`

**Comment by martin-molina** [comment]
If you are using droneSimulator, you'll have to consider that it does not generate images from camera.

**Comment by QiuMingZS** [comment]
Can I use the camera in the simulation?

**Comment by QiuMingZS** [comment]
Is there any other way to simulate using the camera?
