### ISSUE TITLE
Issue with vrep and aerostack

### ISSUE THREAD

**Issue by jimis093** [Vision4UAV/Aerostack#37]
Hey your project is really nice 
Can you help me to find a way to setting up the vrep with aerostack ? Thanx !

**Comment by martin-molina** [comment]
In the next version of Aerostack (version 3.0) we plan to include an example describing how to use Aerostack with V-Rep. We expect to release version 3.0 at the end of May or the beginning of June. Thanks.

**Comment by jimis093** [comment]
Thanx for response !!! i want to ask you if i can with this version to use the vrep ! Thanx

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Τετ, 3 Απρ, 2019 στις 4:17 μ.μ., ο χρήστηςMartin Molina<notifications@github.com> έγραψε:   
In the next version of Aerostack (version 3.0) we plan to include an example describing how to use Aerostack with V-Rep. We expect to release version 3.0 at the end of May or the beginning of June. Thanks.

**Comment by martin-molina** [comment]
Yes, but you have to create the interfaces.

**Comment by jimis093** [comment]
Thanx for helping !!!!!!

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Πέμ, 4 Απρ, 2019 στις 12:49 π.μ., ο χρήστηςMartin Molina<notifications@github.com> έγραψε:   
Yes, but you have to create the interfaces.

**Comment by jimis093** [comment]
The interfaves of ros or the vrep ? 

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Πέμ, 4 Απρ, 2019 στις 1:38 π.μ., ο χρήστηςdimitris dimitris<gdimitris.connex@yahoo.gr> έγραψε:   Thanx for helping !!!!!!

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Πέμ, 4 Απρ, 2019 στις 12:49 π.μ., ο χρήστηςMartin Molina<notifications@github.com> έγραψε:   
Yes, but you have to create the interfaces.

**Comment by jimis093** [comment]
Plz can you tell me a few things about this ? I need for exam work ...

**Comment by martin-molina** [comment]
You can use inter-process communication provided by ROS (e.g., ROS topics) to communicate VRep and Aerostack.

**Comment by jimis093** [comment]
hello finaly i made it to connect the vrep with aerostack , i want to ask you how my drone will follows as path some images ?  thanx :)

    Στις Παρασκευή, 5 Απριλίου 2019, 10:19:37 π.μ. EEST, ο χρήστης Martin Molina <notifications@github.com> έγραψε:  
 
 
You can use inter-process communication provided by ROS (e.g., ROS topics) to communicate VRep and Aerostack.

**Comment by martin-molina** [comment]
Could you please give us more details to clarify your question "how my drone will follows as path some images ?". Thank you.

**Comment by jimis093** [comment]
hello , i have this  refinery and i want my drone to follow the pipes . can you tell me how i can do this ? thanx 

    Στις Δευτέρα, 8 Απριλίου 2019, 2:54:45 μ.μ. EEST, ο χρήστης Martin Molina <notifications@github.com> έγραψε:  
 
 
Could you please give us more details to clarify your question "how my drone will follows as path some images ?". Thank you.

**Comment by jimis093** [comment]
also i have an issue, when the drone is in trajectrory mode , then it can not move correct, but when i control it from keyboard it moves perfect .. what can i do for that ? thanx  
    Στις Δευτέρα, 8 Απριλίου 2019, 2:54:45 μ.μ. EEST, ο χρήστης Martin Molina <notifications@github.com> έγραψε:  
 
 
Could you please give us more details to clarify your question "how my drone will follows as path some images ?". Thank you.

**Comment by jimis093** [comment]
Hello again , i have some questions , First of all what  can i do with exporting files from aerostack ( i mean how i can use the exporting files , yaml and python files in a project from vrep ) ?
Sec , the drone of vrep and the 'drone  visual maker of aerostack ' they are confused and i get something like that (img 111111111111111111111111).


And with what way can i have α resault like this https://www.youtube.com/watch?v=0Z3Qgj1BhnM ? 

thanx .. Sory for i beeing annoying but is to immportant for me ! thnx 





    Στις Δευτέρα, 8 Απριλίου 2019, 2:54:45 μ.μ. EEST, ο χρήστης Martin Molina <notifications@github.com> έγραψε:  
 
 
Could you please give us more details to clarify your question "how my drone will follows as path some images ?". Thank you.

**Comment by jimis093** [comment]
Hello again , i have some questions , First of all what  can i do with exporting files from aerostack ( i mean how i can use the exporting files , yaml and python files in a project from vrep ) ?
Sec , the drone of vrep and the 'drone  visual maker of aerostack ' they are confused and i get this (img 111111111111111111111111).


And with what way can i have α resault like this https://www.youtube.com/watch?v=0Z3Qgj1BhnM ? 

thanx .. Sory for i beeing annoying but is to immportant for me ! thnx

**Comment by martin-molina** [comment]
Hi, it is difficult for us to help you now with this issue because we don't have an implemented reusable solution yet. As I said, we are working now to have it ready for the next release (in May or June). However, if we have it before, we will let you know. Thank you.
