### ISSUE TITLE
Mutil-UAVs cooperation 

### ISSUE THREAD

**Issue by MOMOHTT** [Vision4UAV/Aerostack#38]
Dear professor：
   I want to achieve Muti-UAVs cooperation using Aerosatck，but I don’t know how to run mutil-UAV simulation programs in a GUI, and how to achieve inter-communication between UAVs.

**Comment by martin-molina** [comment]
If you want to use a simulator (e.g., Gazebo or VREP) with different UAVs, you need to program new interfaces between the simulator and Aerostack (through ROS). Unfortunately, we don't provide these interfaces with Aerostack 2.1, but we are working to include them in future versions.

**Comment by MOMOHTT** [comment]
Thank you so much for your reply！And I'm looking forward to the Aerosatck3.0.
签名由网易邮箱大师定制
On 4/22/2019 18:56，Martin Molina<notifications@github.com> wrote：

If you want to use a simulator (e.g., Gazebo or VREP) with different UAVs, you need to program new interfaces between the simulator and Aerostack (through ROS). Unfortunately, we don't provide these interfaces with Aerostack 2.1, but we are working to include them in future versions.

**Comment by MOMOHTT** [comment]
Dear professor:
    I have two questions. first，I have read some papers published by your team. The experimental part is done indoors. If I want to use outdoor scenes, do I have to implement an outdoor positioning functional component (such as GPS) by myself, and then add it to the launcher file? Second，Can multiple UAVs be placed in Aerostack for simulation? If can, how to do this？

**Comment by martin-molina** [comment]
> do I have to implement an outdoor positioning functional component (such as GPS) by myself, and then add it to the launcher file? 
Yes, this is the approach.
> Can multiple UAVs be placed in Aerostack for simulation?
You have to create an instance of Aerostack for each UAV.
