### ISSUE TITLE
simulation using rotors

### ISSUE THREAD

**Issue by QiuMingZS** [Vision4UAV/Aerostack#39]
Hi, in the stack, I find the part of the rotors_simulator, and try to use it. But I find that in the file  README,  the ros version is indigo, but the Aerostack is corresponded to kinetic,.
![Screenshot from 2019-04-22 21-02-18](https://user-images.githubusercontent.com/44081667/56501791-a7dc7280-6542-11e9-84d9-792cfddaab75.png)

**Comment by hridaybavle** [comment]
Hi, 

The aerostack will install the proper rotors version for you when you install the aerostack. You will have it installed properly if you have already installed Aerostack. You dont need to follow the rotors instructions separately.

**Comment by QiuMingZS** [comment]
thanks😁 王冠政 邮箱：guanzhengnpu@gmail.com 签名由 网易邮箱大师 定制 On 04/22/2019 22:13, Hriday Bavle wrote: Hi, The aerostack will install the proper rotors version for you when you install the aerostack. You will have it installed properly if you have already installed Aerostack. You dont need to follow the rotors instructions separately. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by QiuMingZS** [comment]
Thank you so much
