### ISSUE TITLE
Problem in saving custom behavior tree

### ISSUE THREAD

**Issue by Arsalan66** [Vision4UAV/Aerostack#50]
![IMG_5159](https://user-images.githubusercontent.com/53790445/66013822-1e17d480-e4e6-11e9-9f43-2dc04615897d.JPG)

Salam and hi , I'm encountering a problem in creating a custom behaviour tree in project Behavior tree mission with "Drone simulator", when I launch this command $ ./mission_editor_launcher.sh
It outputs results as shown in picture and does not save in yaml file
Any help/assistance to solve problem would be highly appreciated

**Comment by rodelgo7al** [comment]
Hello, export your tree ("Export" button) with the name "behavior_tree_mission_file" (without .yaml) to your documents folder or desktop. Delete the old behavior_tree_mission_file.yaml located in /mission/ and replaced it with the new one.

**Comment by Arsalan66** [comment]
Thanks for response, I'll let you know the progress

**Comment by Arsalan66** [comment]
Thanks brother , it worked
