### ISSUE TITLE
Issue with mapping at lidar basic mission

### ISSUE THREAD

**Issue by antoniSepu** [Vision4UAV/Aerostack#59]
Hello everyone!

I am having trouble trying to run the basic lidar mission project in my ubuntu 18.04.3LTS with ros melodic.
Firstly I run the gazebo launcher successfully but when launching the main I got this error on the tfs:
> Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree
[frames.pdf](https://github.com/Vision4UAV/Aerostack/files/3964911/frames.pdf)

I add the rqt graph frames.pdf of that moment.

I am pretty new in the ros environment so every kind of help would be appreciated.

Thank you!

**Comment by rodelgo7al** [comment]
Hello, the project "basic lidar mission" has been tested on ubuntu 16 and ros kinetic, it has some problems on ubuntu 18. We want to maximize compatibility in future updates.

Anyway, that error doesn't affect the mission.
