### ISSUE TITLE
installation error, getting cmake error while installing

### ISSUE THREAD

**Issue by manivara507** [Vision4UAV/Aerostack#61]
![Screenshot from 2020-03-28 16-34-14](https://user-images.githubusercontent.com/52490338/77850547-f386aa00-71f0-11ea-9c20-7ff65e1fb4a8.png)

**Comment by manivara507** [comment]
![Screenshot from 2020-03-29 20-39-22](https://user-images.githubusercontent.com/52490338/77852659-76156680-71fd-11ea-8a0f-644b43413ec2.png)


what is the user name and password for aerostack installation

**Comment by rodelgo7al** [comment]
Hello, this was a bug, I've uploaded some changes to the repository. Delete workspace and temp folders and install again Aerostack.

Thank you.
