### ISSUE TITLE
how to solve Cmake error

### ISSUE THREAD

**Issue by manivara507** [Vision4UAV/Aerostack#63]
![Screenshot from 2020-04-10 13-40-44](https://user-images.githubusercontent.com/52490338/78975068-f65a9680-7b30-11ea-8417-7ef7ebcab252.png)

**Comment by rodelgo7al** [comment]
Try to install some ros dependencies:

`sudo apt-get install ros-melodic-octomap ros-melodic-octomap-mapping ros-melodic-octomap-msgs ros-melodic-octomap-ros ros-melodic-octomap-rviz-plugins ros-melodic-octomap-server`

**Comment by ted-15** [comment]
![Screenshot from 2020-04-14 01-58-12](https://user-images.githubusercontent.com/62805315/79158242-96dfdd80-7df3-11ea-9aa0-9ad616868ebd.png)


I am facing similar error also i have attached the screenshot of the same. Due to this error configuration is becoming incomplete and shows cmake error. Help me with finding resolution of it.

Thanks in advance.

**Comment by rodelgo7al** [comment]
I think you should reinstall ros melodic and Aerostack. Delete workspace and temp folder and execute this command:

> sudo apt-get remove ros-*

Then follow these steps: http://wiki.ros.org/melodic/Installation/Ubuntu

And reinstall Aerostack. Thank you.

**Comment by ted-15** [comment]
![Screenshot from 2020-04-19 14-52-11](https://user-images.githubusercontent.com/62805315/79684267-8f825f00-824d-11ea-9a7e-099472fe0dfd.png)

i removed ros and installed it again. also i followed the installation procedure given but still i get an error and it says configuration incomplete. I have attached the screenshot 

how to resolve it as i am tried many times still i get the same error.

Thanks

**Comment by ted-15** [comment]
i have fixed previous error using the command sudo apt-get install ros-$ROS_DISTRO-mavlink and then followed by an another error 

![image](https://user-images.githubusercontent.com/62805315/79687419-b9934b80-8264-11ea-8838-3d2888e47959.png)

and then i used this command to fix it sudo apt-get install ros-melodic-octomap ros-melodic-octomap-mapping ros-melodic-octomap-msgs ros-melodic-octomap-ros ros-melodic-octomap-rviz-plugins ros-melodic-octomap-server

after which i am facing the current error about Could not find a package configuration file provided by "opencv_apps" with
  any of the following names:

    opencv_appsConfig.cmake
    opencv_apps-config.cmake

i have attached screenshot also.
![Screenshot from 2020-04-19 17-34-55](https://user-images.githubusercontent.com/62805315/79687365-63bea380-8264-11ea-9278-560106c3895d.png)

help me to resolve it.

**Comment by ted-15** [comment]
![Screenshot from 2020-04-20 15-00-46](https://user-images.githubusercontent.com/62805315/79736865-16037300-8318-11ea-9ba6-048727c79c5c.png)

Also i have fixed the previous errors. now i am facing an new error for which i have attached the screenshot. also the error below 

[ 74%] Generating qrc_images.cpp
RCC: Error in '/home/solomon/workspace/ros/aerostack_catkin_ws/src/aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/src/view/resources/images.qrc': Cannot find file 'images/Kompaß360.png'
aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/build.make:134: recipe for target 'aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/qrc_images.cpp' failed
make[2]: *** [aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/qrc_images.cpp] Error 1
CMakeFiles/Makefile2:44179: recipe for target 'aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/all' failed
make[1]: *** [aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Linking CXX shared library /home/solomon/workspace/ros/aerostack_catkin_ws/devel/lib/liblib_cvgloggerROS.so
[ 74%] Built target lib_cvgloggerROS
[ 74%] Building CXX object aerostack_stack/stack/execution_control_system/behavior_systems/navigation_with_lidar/CMakeFiles/navigation_with_lidar.dir/src/source/behavior_generate_path_with_occupancy_grid.cpp.o
[ 74%] Linking CXX shared library /home/solomon/workspace/ros/aerostack_catkin_ws/devel/lib/libnavigation_with_lidar.so
[ 74%] Built target navigation_with_lidar
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

kindly help me to resolve me this error. Thanks in advance.

**Comment by rodelgo7al** [comment]
Which ubuntu version are you using?

**Comment by ted-15** [comment]
I am using Ubuntu 18.04 lts

**Comment by ted-15** [comment]
Also i have fixed the previous errors. now i am facing an new error for which i have attached the screenshot. also the error below

[ 74%] Generating qrc_images.cpp
RCC: Error in '/home/solomon/workspace/ros/aerostack_catkin_ws/src/aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/src/view/resources/images.qrc': Cannot find file 'images/Kompaß360.png'
aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/build.make:134: recipe for target 
'aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/qrc_images.cpp' failed
make[2]: *** [aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/qrc_images.cpp] Error 1
CMakeFiles/Makefile2:44179: recipe for target 'aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/all' failed
make[1]: *** [aerostack_stack/stack/ground_control_system/graphical_user_interface/parameters_viewer_process/CMakeFiles/parameters_viewer_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Linking CXX shared library /home/solomon/workspace/ros/aerostack_catkin_ws/devel/lib/liblib_cvgloggerROS.so
[ 74%] Built target lib_cvgloggerROS
[ 74%] Building CXX object aerostack_stack/stack/execution_control_system/behavior_systems/navigation_with_lidar/CMakeFiles/navigation_with_lidar.dir/src/source/behavior_generate_path_with_occupancy_grid.cpp.o
[ 74%] Linking CXX shared library /home/solomon/workspace/ros/aerostack_catkin_ws/devel/lib/libnavigation_with_lidar.so
[ 74%] Built target navigation_with_lidar
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

please someone help me to resolve me this error. Thanks in advance.

![Screenshot from 2020-04-20 15-00-46](https://user-images.githubusercontent.com/62805315/80526453-62058600-89b0-11ea-9d54-0da1ea680763.png)

**Comment by ted-15** [comment]
Hello Sir,

I am getting this qrc_images.cpp error while I am installing always.

Can you please help me with this to resolve? I having been doing this for
months now but still I didn't find any solution. after the new version this
error for me is not fixed.

Kindly help me out.

PFA.

Waiting for your reply.
