### ISSUE TITLE
I'm not able to run phython based missions 

### ISSUE THREAD

**Issue by manivara507** [Vision4UAV/Aerostack#66]
I'm not able to run python based examples and I'm getting the below error.
ERROR: Service [/drone111/python_based_mission_interpreter_process/start] is not available.

**Comment by rodelgo7al** [comment]
Hello, can you tell me more information about the error?

The problem is related to the "python_based_mission_interpreter_process" terminal, maybe you don't have installed pyinotify.

Check the terminal of that specific process and its error
