### ISSUE TITLE
Could anyone help me in resolving this issue?

### ISSUE THREAD

**Issue by JakubBrzozowski97** [Vision4UAV/Aerostack#68]
i have fixed previous error using the command sudo apt-get install ros-$ROS_DISTRO-mavlink and then followed by an another error 

![image](https://user-images.githubusercontent.com/62805315/79687419-b9934b80-8264-11ea-8838-3d2888e47959.png)

and then i used this command to fix it sudo apt-get install ros-melodic-octomap ros-melodic-octomap-mapping ros-melodic-octomap-msgs ros-melodic-octomap-ros ros-melodic-octomap-rviz-plugins ros-melodic-octomap-server

after which i am facing the current error about Could not find a package configuration file provided by "opencv_apps" with
  any of the following names:

    opencv_appsConfig.cmake
    opencv_apps-config.cmake

i have attached screenshot also.
![Screenshot from 2020-04-19 17-34-55](https://user-images.githubusercontent.com/62805315/79687365-63bea380-8264-11ea-9278-560106c3895d.png)

help me to resolve it.

_Originally posted by @ted-15 in https://github.com/Vision4UAV/Aerostack/issues/63#issuecomment-616118531_

**Comment by martin-molina** [comment]
In one week approximately we are planning to publish a new version of Aerostack (version 4.0). I would recommend to wait until then because it is going to be more efficient and with additional tools for installation.
