### ISSUE TITLE
DRONE_STACK  is not set

### ISSUE THREAD

**Issue by AloshkaD** [Vision4UAV/Aerostack#8]
I have the Aerostack fully installed and the IBVS as well on an Ubuntu 14.4  
When I run "${IBVS_STACK}/launchers/parrot_IBVSController_launcher_Release.sh " I get the error below. Also, the  DRONE_STACK folder does not exist. I need to use is for adding the config file to "\Config " directory for the camera. 

Invalid <arg> tag: environment variable 'DRONE_STACK' is not set. 

Arg xml is <arg default="$(env DRONE_STACK)" name="my_stack_directory"/>
The traceback for the exception was written to the log file

![image](https://cloud.githubusercontent.com/assets/10216145/16703961/8f33ec46-4537-11e6-94ea-4843158dd946.png)

Is the DRONE_STACK as same as aerostack_stack? If yes  how do I change it so I would run my commands without getting the mentioned error?
![image](https://cloud.githubusercontent.com/assets/10216145/16704305/1a92ac5c-453b-11e6-91b0-0ddf72a6779c.png)

**Comment by joselusl** [comment]
Hi,
In the previous versions of Aerostack (V0.x), we used two environmental variables: $DRONE_STACK and $DRONE_WORKSPACE.
Now, in the current version (V1.x), we changed these variables to: $AEROSTACK_STACK and $AEROSTACK_WORKSPACE.
We tried to update all the launchers, but we might have missed some.
Please, if you ever see one of the old environmental variables, change them to the new ones. Everything should work.
Bests

**Comment by AloshkaD** [comment]
Thank you, that worked for me!
